In [172]:
# 导入:
from sqlalchemy import Column, String, create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

# 创建对象的基类:
Base = declarative_base()

# 定义User对象:
class User(Base):
    # 表的名字:
    __tablename__ = 'user'

    # 表的结构:
    id = Column(String(20), primary_key=True)
    name = Column(String(20))

# 初始化数据库连接:
engine = create_engine('mysql+mysqlconnector://root:password@localhost:3306/test')

# 创建DBSession类型:
DBSession = sessionmaker(bind=engine)

Hello World!
Hello World!


In [ ]:
# 创建session对象:
session = DBSession()
# 创建新User对象:
new_user = User(id='5', name='Bob')
# 添加到session:
session.add(new_user)
# 提交即保存到数据库:
session.commit()
# 关闭session:
session.close()

In [35]:
from __future__ import annotations
from typing import Optional


class SingletonMeta(type):
    """
    The Singleton class can be implemented in different ways in Python. Some
    possible methods include: base class, decorator, metaclass. We will use the
    metaclass because it is best suited for this purpose.
    """

    _instance: Optional[Singleton] = None

    def __call__(self) -> Singleton:
        if self._instance is None:
            self._instance = super().__call__()
        return self._instance


class Singleton(metaclass=SingletonMeta):
    def some_business_logic(self):
        """
        Finally, any singleton should define some business logic, which can be
        executed on its instance.
        """

        # ...


if __name__ == "__main__":
    # The client code.

    s1 = Singleton()
    s2 = Singleton()

    if id(s1) == id(s2):
        print("Singleton works, both variables contain the same instance.")
    else:
        print("Singleton failed, variables contain different instances.")

Singleton works, both variables contain the same instance.


In [17]:
j

5

In [39]:
import jieba
import jieba.posseg as pseg

In [40]:
import pandas as pd 
import jieba 
from keras.layers.merge import concatenate 
from keras.utils import to_categorical 
from keras.preprocessing.text import Tokenizer 
from keras.preprocessing.sequence import pad_sequences 
from tensorflow import * 
from keras.layers.embeddings import Embedding 
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dropout, Dense, Input, Lambda 
from sklearn.metrics import accuracy_score, f1_score
from keras.models import Model 
import numpy as np

In [4]:
metrics

<module 'tensorflow_core.python.keras.api._v2.keras.metrics' from '/Anaconda/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/api/_v2/keras/metrics/__init__.py'>

In [2]:
print(list(jieba.cut('查询工程险的产品方案')))
print(list(pseg.cut('查询工程险的产品方案', HMM=0)))

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.957 seconds.
Prefix dict has been built succesfully.


['查询', '工程', '险', '的', '产品', '方案']
[pair('查询', 'v'), pair('工程', 'n'), pair('险', 'a'), pair('的', 'uj'), pair('产品', 'n'), pair('方案', 'n')]


In [3]:
cut = lambda x: list(pseg.cut(x))

In [4]:
cut('什么是企财险')

[pair('什么', 'r'), pair('是', 'v'), pair('企', 'n'), pair('财险', 'n')]

In [5]:
cut('那麻烦您帮我查一下商机可以吗')

[pair('那', 'r'),
 pair('麻烦', 'an'),
 pair('您', 'r'),
 pair('帮', 'v'),
 pair('我', 'r'),
 pair('查', 'v'),
 pair('一下', 'm'),
 pair('商机', 'n'),
 pair('可以', 'c'),
 pair('吗', 'y')]

In [15]:
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [29]:
import pandas as pd
import numpy as np
import xgboost as xgb
from tqdm import tqdm
from sklearn.svm import SVC
from keras.models import Sequential
from keras.layers.recurrent import LSTM, GRU
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.embeddings import Embedding
from keras.layers.normalization import BatchNormalization
from keras.utils import np_utils
from sklearn import preprocessing, decomposition, model_selection, metrics, pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from keras.layers import GlobalMaxPooling1D, Conv1D, MaxPooling1D, Flatten, Bidirectional, SpatialDropout1D
from keras.preprocessing import sequence, text
from keras.callbacks import EarlyStopping
from nltk import word_tokenize
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

In [108]:
def cal_vector(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [107]:
a = np.array([5, 1, 0, 2, 2])
b = np.array([1, 5, 2, 5, 5])
cal_vector(a, b)

0.5752237416355278

In [21]:
import pandas as pd
import numpy as np

In [9]:
a = np.arange(15).reshape(5, 3)
a 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
a.dtype.name

'int64'

In [12]:
type(a)

numpy.ndarray

In [13]:
a.dtype

dtype('int64')

In [20]:
b = np.array([[1, 2], [3, 4]], dtype=complex)

In [18]:
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [21]:
np.empty((2, 3))

array([[6.90764959e-310, 4.67798224e-310, 6.90761144e-310],
       [1.89639471e+262, 6.90761145e-310, 4.67798224e-310]])

In [27]:
np.arange(100000).reshape(100, 1000)
np.set_printoptions(threshold='nan')

array([[    0,     1,     2, ...,   997,   998,   999],
       [ 1000,  1001,  1002, ...,  1997,  1998,  1999],
       [ 2000,  2001,  2002, ...,  2997,  2998,  2999],
       ...,
       [97000, 97001, 97002, ..., 97997, 97998, 97999],
       [98000, 98001, 98002, ..., 98997, 98998, 98999],
       [99000, 99001, 99002, ..., 99997, 99998, 99999]])

In [29]:
a = np.array([20, 30, 40, 50])

In [30]:
b = np.arange(4)

In [32]:
a

array([20, 30, 40, 50])

In [31]:
b

array([0, 1, 2, 3])

In [33]:
a - b

array([20, 29, 38, 47])

In [34]:
b ** 2

array([0, 1, 4, 9])

In [36]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [37]:
a < 35

array([ True,  True, False, False])

In [39]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

In [40]:
A

array([[1, 1],
       [0, 1]])

In [41]:
B

array([[2, 0],
       [3, 4]])

In [42]:
A * B

array([[2, 0],
       [0, 4]])

In [43]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [46]:
a = np.ones((2, 3), dtype=int)

In [45]:
b = np.random.random((2, 3))

In [47]:
a *= 3

In [48]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [49]:
b += a

In [50]:
b

array([[3.68974622, 3.36145827, 3.21190413],
       [3.12195083, 3.42183636, 3.88184055]])

In [51]:
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])